var namespacePurrNet_1_1Transports =
[
    [ "AutomaticCloudSetups", "classPurrNet_1_1Transports_1_1AutomaticCloudSetups.html", null ],
    [ "ByteData", "structPurrNet_1_1Transports_1_1ByteData.html", null ],
    [ "ClientJoinInfo", "structPurrNet_1_1Transports_1_1ClientJoinInfo.html", null ],
    [ "CompositeTransport", "classPurrNet_1_1Transports_1_1CompositeTransport.html", "classPurrNet_1_1Transports_1_1CompositeTransport" ],
    [ "Connection", "structPurrNet_1_1Transports_1_1Connection.html", null ],
    [ "FragmentationLayer", "classPurrNet_1_1Transports_1_1FragmentationLayer.html", "classPurrNet_1_1Transports_1_1FragmentationLayer" ],
    [ "FragmentDropInfo", "structPurrNet_1_1Transports_1_1FragmentDropInfo.html", "structPurrNet_1_1Transports_1_1FragmentDropInfo" ],
    [ "GenericTransport", "classPurrNet_1_1Transports_1_1GenericTransport.html", "classPurrNet_1_1Transports_1_1GenericTransport" ],
    [ "HostJoinInfo", "structPurrNet_1_1Transports_1_1HostJoinInfo.html", null ],
    [ "IConnectable", "interfacePurrNet_1_1Transports_1_1IConnectable.html", null ],
    [ "IListener", "interfacePurrNet_1_1Transports_1_1IListener.html", null ],
    [ "ITransport", "interfacePurrNet_1_1Transports_1_1ITransport.html", null ],
    [ "LocalTransport", "classPurrNet_1_1Transports_1_1LocalTransport.html", null ],
    [ "NetworkSimulation", "structPurrNet_1_1Transports_1_1NetworkSimulation.html", null ],
    [ "PeerInfo", "classPurrNet_1_1Transports_1_1PeerInfo.html", null ],
    [ "PurrTransport", "classPurrNet_1_1Transports_1_1PurrTransport.html", "classPurrNet_1_1Transports_1_1PurrTransport" ],
    [ "Relayers", "structPurrNet_1_1Transports_1_1Relayers.html", null ],
    [ "RelayServer", "structPurrNet_1_1Transports_1_1RelayServer.html", null ],
    [ "UDPTransport", "classPurrNet_1_1Transports_1_1UDPTransport.html", "classPurrNet_1_1Transports_1_1UDPTransport" ],
    [ "WebTransport", "classPurrNet_1_1Transports_1_1WebTransport.html", null ],
    [ "FragmentDropReason", "namespacePurrNet_1_1Transports.html#aea2a3e5dce25f82108029db663db2216", null ],
    [ "MTUBehaviour", "namespacePurrNet_1_1Transports.html#a995a08be1b68a789fb34d53016826d8e", null ],
    [ "MTUExceededBehaviour", "namespacePurrNet_1_1Transports.html#aa5445fa7ab9a4640b501543bb11b5701", null ]
];